### ISSUE TITLE
IOError when converting BioNLP format to CoNLL format

### ISSUE THREAD

**Issue by xw-yao** [OntoGene/craft-st#1]
python 2.7
./bionlp2conll.sh GO_BP /Users/.../craft-st/CRAFT/BP
ln: illegal option -- t
usage: ln [-Ffhinsv] source_file [link_name]
       ln [-Ffhinsv] source_file ... linkname_dir
       link source_file link_name
Traceback (most recent call last):
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 136, in <module>
    sys.exit(main(sys.argv))
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 126, in main
    convert_directory(path, args)
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 104, in convert_directory
    convert_files(files, options)
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 108, in convert_files
    document = read_ann(fn, options)
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 64, in read_ann
    with codecs.open(txtfilename, 'rU', encoding=encoding) as t_in:
  File "/Users/xwyao/opt/anaconda3/envs/py2/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: './11319941.txt'
Traceback (most recent call last):
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 136, in <module>
    sys.exit(main(sys.argv))
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 126, in main
    convert_directory(path, args)
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 104, in convert_directory
    convert_files(files, options)
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 108, in convert_files
    document = read_ann(fn, options)
  File "/Users/xwyao/Desktop/NLP/craft-st/standoff2conll/standoff2conll.py", line 64, in read_ann
    with codecs.open(txtfilename, 'rU', encoding=encoding) as t_in:
  File "/Users/xwyao/opt/anaconda3/envs/py2/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: './11532192.txt'
...
Appreciated any help that how to fix this

**Comment by lfurrer** [comment]
It looks like you're using a shell with an `ln` command that doesn't support the `-t` option.
I didn't test the shell scripts for cross-platform compatibility.

**Comment by xw-yao** [comment]
Thank you!
Modified 'ln -s -t . ${CRAFT}/articles/txt/*.txt' to 'ln -s ${CRAFT}/articles/txt/*.txt .' to work on bash or zsh.
